// src/features/exercises/constants/exerciseTaxonomy.js

export const PRIMARY_MUSCLES = [
  "chest",
  "lats",
  "upper_back",
  "lower_back",
  "traps",
  "front_delts",
  "side_delts",
  "rear_delts",
  "biceps",
  "triceps",
  "forearms",
  "neck",
  "abs",
  "obliques",
  "core",
  "glutes",
  "quadriceps",
  "hamstrings",
  "calves",
  "adductors",
  "abductors",
  "full_body",
  "cardio",
  "conditioning",
];

export const SECONDARY_MUSCLES = [
  "chest",
  "lats",
  "upper_back",
  "lower_back",
  "traps",
  "front_delts",
  "side_delts",
  "rear_delts",
  "biceps",
  "triceps",
  "forearms",
  "neck",
  "abs",
  "obliques",
  "core",
  "glutes",
  "quadriceps",
  "hamstrings",
  "calves",
  "adductors",
  "abductors",
];

export const EQUIPMENT = [
  "barbell",
  "dumbbell",
  "cable",
  "machine",
  "smith_machine",
  "kettlebell",
  "resistance_band",
  "bodyweight",
  "ez_bar",
  "trap_bar",
  "landmine",
  "bench",
  "pull_up_bar",
  "dip_station",
  "other",
];

export const EXERCISE_TYPES = [
  "strength",
  "hypertrophy",
  "power",
  "endurance",
  "mobility",
  "cardio",
  "conditioning",
];

export const MOVEMENT_PATTERNS = [
  "horizontal_push",
  "horizontal_pull",
  "vertical_push",
  "vertical_pull",
  "squat",
  "hinge",
  "lunge",
  "carry",
  "rotation",
  "anti_rotation",
  "anti_extension",
  "anti_lateral_flexion",
  "isolation",
  "locomotion",
  "other",
];
